### ISSUE TITLE
Use a different way to build ZIP for instawp

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/trustedlogin-connector#154]
Zip build is fixed: #150 is  a test.

In that workflow [this step](https://github.com/trustedlogin/vendor/blob/develop/.github/workflows/instawp.yml#L18-L25) uses Plugin Machine Github action to build a zip and upload it to the one Plugin Machine service that is still running. That makes the zip availble for download here: https://github.com/trustedlogin/vendor/blob/develop/.github/workflows/instawp.yml#L37 so InstaWP can use it.

No rush, but can we stop using Plugin Machine for this? If the zip file was committed to the repo, by a different build process, then you could [use that URL with InstaWP](https://github.com/trustedlogin/vendor/blob/develop/.github/workflows/instawp.yml#L37)

**Comment by zackkatz** [comment]
Implemented in https://github.com/trustedlogin/trustedlogin-connector/commit/1087cc6f017df76a2cab6d1591a94d91008b553f
